name: Update Translations

on:
  workflow_dispatch:

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TRANSIFEX_TOKEN }}
          args: pull -a --force
      - run: |
          git config --global user.name "Traccar Bot"
          git config --global user.email "support@traccar.org"
          for f in src/resources/l10n/*.json; do
            [[ $f == */en.json ]] && continue
            diff -q "$f" src/resources/l10n/en.json && continue
            git diff --quiet -- "$f" || git add "$f"
          done
          git diff --cached --quiet || git commit -m "Update translations"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
